- apt:
    name: python-pip

- pip:
    name: docker-py

- docker:
    name: webapp1
    image: training/webapp
    command: python app.py
    ports: 8001:5000

- docker:
    name: webapp2
    image: training/webapp
    command: python app.py
    ports: 8002:5000

- docker:
    name: webapp3
    image: training/webapp
    command: python app.py
    ports: 8003:5000

- debug:
    msg: "Three containers with training Flask app on 8001,8002,8003"
